# Generated by Django 2.0 on 2019-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.TextField()),
                ('suburb', models.TextField()),
                ('state', models.TextField()),
                ('dc', models.TextField()),
                ('detail_type', models.TextField()),
                ('lat', models.TextField()),
                ('ion', models.TextField()),
            ],
        ),
    ]
