# Generated by Django 2.0 on 2019-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetailsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dc', models.CharField(max_length=100)),
                ('detail_type', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('ion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='dc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='detail_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='ion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='postcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrydetails',
            name='suburb',
            field=models.CharField(max_length=100),
        ),
    ]
