# Generated by Django 2.0 on 2019-06-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190611_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryDetailsTest',
        ),
    ]
