# Generated by Django 2.0 on 2019-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_myitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myitems',
            name='name',
        ),
        migrations.AddField(
            model_name='myitems',
            name='category',
            field=models.CharField(choices=[('Trouser', 'Trouser'), ('Shorts', 'Shorts'), ('T-Shirts', 'T-Shirts'), ('Shoe', 'Shoe'), ('Underwear', 'Underwear'), ('Singlet', 'Singlet'), ('Boxer', 'Boxer'), ('Pant', 'Pant'), ('Socks', 'Socks'), ('Trouser', 'Trouser')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
