# Generated by Django 2.0 on 2019-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190927_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitems',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
