# Generated by Django 2.0 on 2019-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190927_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitems',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
