# Generated by Django 2.0 on 2019-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190704_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='myitems',
            name='category',
            field=models.CharField(choices=[('Trouser', 'Trouser'), ('Shorts', 'Shorts'), ('T-Shirts', 'T-Shirts'), ('Shoe', 'Shoe'), ('Underwear', 'Underwear'), ('Singlet', 'Singlet'), ('Boxer', 'Boxer'), ('Pant', 'Pant'), ('Socks', 'Socks')], max_length=20),
        ),
    ]
