# Generated by Django 2.0 on 2019-09-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_cart_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myitems',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
