# Generated by Django 2.0 on 2019-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20190707_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='single_price',
            field=models.IntegerField(default=1),
        ),
    ]
