# Generated by Django 2.0 on 2019-07-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_cart_single_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
