# Generated by Django 2.0 on 2019-09-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20190928_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='count',
            new_name='total_count',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='count',
            new_name='total_count',
        ),
    ]
