# Generated by Django 2.0 on 2019-09-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20190928_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cartcategory', to='administrator.Category'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cartsubcategory', to='administrator.SubCategory'),
        ),
    ]
