# Generated by Django 2.0 on 2019-07-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='phonenumber',
        ),
    ]
