# Generated by Django 2.0 on 2019-10-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryDetails',
        ),
    ]
