# Generated by Django 2.0 on 2019-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20190717_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myitems',
            name='size',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
