# Generated by Django 2.0 on 2019-12-09 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20191019_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
