# Generated by Django 2.0 on 2019-07-21 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_pettycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 21, 5, 32, 27, 354469, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
