# Generated by Django 2.0 on 2019-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_cart_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
