# Generated by Django 2.0 on 2019-12-10 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0023_cartitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usercartitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
