# Generated by Django 2.0 on 2019-11-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
