# Generated by Django 2.0 on 2019-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20190717_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepasswordcode',
            name='user_email',
        ),
        migrations.AddField(
            model_name='changepasswordcode',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
