# Generated by Django 2.0 on 2019-11-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191104_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='style',
            field=models.CharField(default='', max_length=60),
        ),
    ]
