# Generated by Django 2.0 on 2019-11-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_index_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
