# Generated by Django 2.0 on 2019-11-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_index_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='size',
        ),
        migrations.RemoveField(
            model_name='indexcategory',
            name='unisex',
        ),
        migrations.AddField(
            model_name='index',
            name='L',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='M',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='S',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='XL',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='XL2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='XL3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='XL4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indexsubcategory',
            name='mycategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indexcategory', to='index.IndexCategory'),
        ),
    ]
