# Generated by Django 2.0 on 2019-11-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_category', to='index.Index'),
        ),
    ]
