# Generated by Django 2.0 on 2019-11-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191108_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
