# Generated by Django 2.0 on 2019-11-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191108_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='L',
        ),
        migrations.RemoveField(
            model_name='index',
            name='M',
        ),
        migrations.RemoveField(
            model_name='index',
            name='S',
        ),
        migrations.RemoveField(
            model_name='index',
            name='XL',
        ),
        migrations.RemoveField(
            model_name='index',
            name='XL2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='XL3',
        ),
        migrations.RemoveField(
            model_name='index',
            name='XL4',
        ),
        migrations.AddField(
            model_name='index',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
