# Generated by Django 2.0 on 2019-11-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191108_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
