# Generated by Django 2.0 on 2019-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20191110_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
