# Generated by Django 2.0 on 2019-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20190525_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='plsn',
            field=models.ImageField(default='1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
