# Generated by Django 2.0 on 2019-06-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_poster_plsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='plsn',
            new_name='plan',
        ),
    ]
