# Generated by Django 2.0 on 2019-06-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20190607_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
