# Generated by Django 2.0 on 2019-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20190607_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
