# Generated by Django 2.0 on 2019-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20190607_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='address',
        ),
        migrations.AddField(
            model_name='poster',
            name='land_size',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='postcode',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='state',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='street_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='street_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='suburb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='unit',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
