# Generated by Django 2.0 on 2019-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20190609_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='unit',
            field=models.TextField(),
        ),
    ]
