# Generated by Django 2.0 on 2019-06-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20190609_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='land_size',
            field=models.CharField(max_length=100),
        ),
    ]
