# Generated by Django 2.0 on 2019-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20190609_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.TextField()),
                ('suburb', models.TextField()),
                ('state', models.TextField()),
                ('dc', models.TextField()),
                ('detail_type', models.TextField()),
                ('lat', models.TextField()),
                ('ion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ninety',
            name='user',
        ),
        migrations.RemoveField(
            model_name='threesixty',
            name='user',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Ninety',
        ),
        migrations.DeleteModel(
            name='ThreeSixty',
        ),
    ]
