# Generated by Django 2.0 on 2019-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20190609_0739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryDetails',
        ),
        migrations.AlterField(
            model_name='poster',
            name='Property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment & Unit', 'Apartment & Unit'), ('Town House', 'Town House'), ('Villa', 'Villa'), ('Land', 'Land'), ('Acreage', 'Acreage'), ('Rural', 'Rural'), ('Block Of Units', 'Block Of Units'), ('Retirement Living', 'Retirement Living')], default='House', max_length=100),
        ),
    ]
