# Generated by Django 2.0 on 2019-09-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_auto_20190629_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='user',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
